name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2


    - name: build
      run: gcc 3_Implementation/src/main_code.c -o main_code.exe
    - name: run
      run : ./main_code.exe


