name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2


    - name: build
      run: gcc 3_Implementation/unit/test_billing-operations.c -o test.exe
    - name: run
      run : ./test.exe


